# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-21 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataLoader',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.NullBooleanField()),
            ],
            options={
                'db_table': 'data_loader',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DataTISensor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation', models.DateTimeField()),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('illuminance', models.FloatField(blank=True, null=True)),
                ('sensor', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'data_ti',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DataWindowsSensor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation', models.DateTimeField()),
                ('tableau', models.NullBooleanField()),
                ('milieu', models.NullBooleanField()),
                ('fond', models.NullBooleanField()),
            ],
            options={
                'db_table': 'data_window',
                'managed': True,
            },
        ),
    ]
