# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-06 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataLoader',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'data_loader',
                'managed': True,
            },
        ),
    ]
